{
  latestPrices(first: 100) {
    asset
    pricingAsset
    poolId {
      name
      symbol
      tokens {
        name
        symbol
        priceRate
      }
    }
    price
  }
  # WETH token on Ethereum
  weth: token(id: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2") {
    address
    name
    symbol
    latestPrice {
      pricingAsset # usdc
      price
    }
    latestUSDPrice
  }
  # USDC token on Ethereum
  usdc: token(id: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48") {
    address
    name
    symbol
    latestPrice {
      pricingAsset # usdt
      price
    }
    latestUSDPrice
  }
  # TETHER token on Ethereum
  usdt: token(id: "0xdac17f958d2ee523a2206206994597c13d831ec7") {
    address
    name
    symbol
    latestPrice {
      pricingAsset # usdc
      price
    }
    latestUSDPrice
  }
}
